#route_name:
#    route: "/Your/Route"
#    controller: Controller:Action

# Your route must finish by a « / »

homepage:
    route: "/"
    controller: "Product:getProducts"

add_product:
    route: "/add/"
    controller: "Product:addProduct"

edit_product:
    route: "/admin/edit/<id>"
    controller: "Product:editThisProduct"
